---

- hosts: local
  connection: local
  gather_facts: False

  vars:
    instance_type: t2.micro
    security_group: ansible_test
    image: ami-807876e3
    user: ubuntu
    keypair: ansible_sit
    region: ap-southeast-2
    count: 1
    keydest: /ext/sit/

  tasks:
  - name: Create security group
    local_action:
      module: ec2_group
      state: present
      name: "{{ security_group }}"
      description: "security group for sit server"
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: Firewall

  - name: Create Key-Pair
    ec2_key:
      name: "{{ keypair }}"
      region: "{{ region }}"
    register: ec2_key

  - name: Save private key
    copy: content="{{ ec2_key.key.private_key }}" dest="{{ keydest }}{{ keypair }}.pem" mode=0600
    when: ec2_key.changed

  - name: Create EC2 instance
    local_action: ec2
                  instance_type={{ instance_type }}
                  image={{ image }}
                  wait=true
                  region={{ region }}
                  keypair={{ keypair }}
                  count={{ count }}
                  group={{ security_group }}
    register: ec2

  - name: Add tag to the instance
    local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
    with_items: "{{ ec2.instances }}"
    args:
      tags:
        Name: SITServer

  - set_fact:
      public_ip: "{{ item.public_ip }}"
    with_items: "{{ ec2.instances }}"

  - name: creating the Inventory
    template:
      src=./templates/inventory.j2
      dest=/ext/sit/inventory


