---

- hosts: TestServers
  sudo: yes
  vars:
    region: ap-southeast-2

  tasks:  
  
  - action: ec2_facts
  - name: terminate the instance
    local_action:
      module: ec2
      state: 'absent'
      region: '{{ region }}'
      instance_ids: "{{ ansible_ec2_instance_id }}"
